[package]
name = "waymark-start-workers"
version = "0.1.0"
edition = "2024"

[dependencies]
waymark-dag = { workspace = true }
waymark-backend-postgres = { workspace = true }
waymark-backend-postgres-migrations = { workspace = true }
waymark = { workspace = true }

anyhow = { workspace = true }
prost = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tokio-util = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
