[package]
name = "waymark-bridge"
version = "0.1.0"
edition = "2024"

[dependencies]
waymark-core-backend = { workspace = true }
waymark-dag = { workspace = true }
waymark-ir-conversions = { workspace = true }
waymark-runner-state = { workspace = true }
waymark-scheduler-backend = { workspace = true }
waymark-scheduler-core = { workspace = true }
waymark-backends-core = { workspace = true }
waymark-backend-postgres = { workspace = true }
waymark-backend-postgres-migrations = { workspace = true }
waymark-workflow-registry-backend = { workspace = true }
waymark-proto = { workspace = true }
waymark-message-conversions = { workspace = true }
waymark = { workspace = true }

anyhow = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
prost = { workspace = true }
rmp-serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tokio-stream = { workspace = true }
tonic = { workspace = true }
tonic-health = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
uuid = { workspace = true }
