[package]
name = "waymark-worker-status-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
waymark-backends-core = { workspace = true }
